### ISSUE TITLE
Receiving FaceLiveness.FaceLivenessDetectionError Code 1

### ISSUE THREAD

**Issue by haarj** [aws-amplify/amplify-ui-swift-liveness#151]
### Describe the bug

Some of my users are receiving 
`FaceLiveness.FaceLivenessDetectionError Code 1`, which in the iOS SDK is a session not found error in `FaceLivenessDetectionError.swift` file,
`public static let sessionNotFound = FaceLivenessDetectionError(
        code: 1,
        message: "Session not found.",
        recoverySuggestion: "Enter a valid session ID."
    )`

We are creating a sessionID server side, passing the session ID to the `FaceLivenessDetectorView` constructor and receive the above error. 

### Steps To Reproduce

```swift
Follow steps above
```

### Expected behavior

Faceliveness Detector view sequence starts and accepts valid sessionID. 

### Swift Liveness Version

1.2.14

### Xcode version

15.4

### Is this a regression?

No

### OS Version

17.5.1

### Device

iPhone 11 Pro

### Specific to simulators

No

### Additional context

This is intermittent. This happens to some users and we are not sure why.

**Comment by ruisebas** [comment]
Hi @haarj, thanks for opening this issue!

Would you mind telling us how you are triggering the creation of the session id on the server side? Also, do you have any relevant logs that you can share? 

Thanks!

**Comment by haarj** [comment]
Hey @ruisebas sure thing. I can't reproduce it on my side. It happens to my users sometimes and it's hard to know why or acquire logs. 

Here is how I am calling it server side. 

`const rekClient = new Rekognition({
      region: "us-east-1",
      credentials: {
            accessKeyId: rekAccessKeyID,    
            secretAccessKey: process.env.AMAZON_REKOGNITION_SECRET_KEY
        }
    });

    const response = await rekClient.createFaceLivenessSession().promise();

    const sessionId = response.SessionId;
    console.log("SessionId:", sessionId);`

**Comment by ruisebas** [comment]
Thanks for providing the code. I assume you are triggering this code in your app, for example with a `Amplify.API.post` call, right?
 
Are you certain that you are receiving a valid response from the service before attempting to show `FaceLivenessDetectorView`? 
Or putting it in another way, are you handling error responses so that `FaceLivenessDetectorView` is **not** being invoked with an old or default `sessionId`?

**Comment by haarj** [comment]
Hey @ruisebas my server side code is always returning a "valid" session Id, which is then passed back to the app and then passed to the `FaceLivenessDetectorView` immediately. What makes this a valid or invalid session ID I'm not sure. Is there a race condition happening where the sessionID I am creating server-side is not recognized by the detector view yet, maybe?

**Comment by ruisebas** [comment]
Hi @haarj, following up on this.

While a race condition would cause this, I think it's unlikely to happen since the session creation is performed on the backend itself. Are you sure you're passing the correct `region` to the Liveness component?

To get more information, would you be able to log these failing session ids and provide them, alongside their time of creation and region? We can then involve the service team and ask them to verify if the sessions are indeed created or what could be going on.

Thanks!

**Comment by ruisebas** [comment]
Oh and sorry to insist on this, but how are you handling errors when attempting to create the session?

```js
const response = await rekClient.createFaceLivenessSession().promise();
const sessionId = response.SessionId;
```

I'm not really familiar with NodeJS, so what happens if `createFaceLivenessSession` returns an error? 
Are you propagating it to your app and handling it inside a `do catch` block?

**Comment by haarj** [comment]
Hey @ruisebas I'll have to release a new version to capture this information. Standby on that front. I'll admit that I don't receive errors on the backend side of things when creating session Ids and so the apps always receive "valid" sessions Ids.

**Comment by ruisebas** [comment]
Thanks!

I think that might be the cause, `createFaceLivenessSession ()` failing and the function returning an invalid/corrupted `sessionId` that is then attempted to be used.

**Comment by haarj** [comment]
Yea so it seems that every now and then a bad sessionID gets created. Anything I can do on my end to fix that?

**Comment by ruisebas** [comment]
To be precise, it's not like a bad sessionId is created, but rather that the [CreateFaceLivenessSession](https://docs.aws.amazon.com/rekognition/latest/APIReference/API_CreateFaceLivenessSession.html) call fails. So a session is never created.

This is outside the scope of the Liveness component, but what you should do is inspect the reason for the failure. You might want to propagate the error to the application so you can handle it gracefully (e.g. showing an error alert/screen instead of trying to show the Liveness component)

**Comment by haarj** [comment]
Well no a sessionID is always being created and I am not receiving any errors. Like you said, a corrupt sessionID is being created but it is still a sessionID that I am passing back to the app.JustinSent from my iPhoneOn Jul 29, 2024, at 12:31 PM, Sebastian Villena ***@***.***> wrote:﻿
To be precise, it's not like a bad sessionId is created, but rather that the CreateFaceLivenessSession call fails. So a session is never created.
This is outside the scope of the Liveness component, but what you should do is inspect the reason for the failure. You might want to propagate the error to the application so you can handle it gracefully (e.g. showing an error alert/screen instead of trying to show the Liveness component)

**Comment by ruisebas** [comment]
Ah, I see. Well, that is still outside the scope of the Liveness component and within the **[AWS Rekognition](https://aws.amazon.com/rekognition/)** service, since they own the **CreateFaceLivenessSession** API. 

I recommend you open an AWS Support case with them and provide the invalid `sessionID`s you're receiving from the service call.

**Comment by haarj** [comment]
Ok thanks!
